apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: reps1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: webapp
      labels:
        app: myapp
    spec:
      containers:
        - name: nginxapp
          image: nginx:latest
          ports:
            - containerPort: 80